// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkePe2VYZuJkzWtYNx9p9JfGO7AQvHC8',
    appId: '1:962831719512:web:b932bcbeba526f874dbe2d',
    messagingSenderId: '962831719512',
    projectId: 'hrverse-a8dc5',
    authDomain: 'hrverse-a8dc5.firebaseapp.com',
    storageBucket: 'hrverse-a8dc5.firebasestorage.app',
    measurementId: 'G-35BVZ2ZWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvhivRpG8i4sT9JDfA-bwLy6Lu20RQiJ4',
    appId: '1:962831719512:android:c647077465ee6fb94dbe2d',
    messagingSenderId: '962831719512',
    projectId: 'hrverse-a8dc5',
    storageBucket: 'hrverse-a8dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdVdNNUVpGuRs4Yb-JU08jdJiyy9OxQYc',
    appId: '1:962831719512:ios:20fb275d0034aa6e4dbe2d',
    messagingSenderId: '962831719512',
    projectId: 'hrverse-a8dc5',
    storageBucket: 'hrverse-a8dc5.firebasestorage.app',
    iosBundleId: 'com.example.hrverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdVdNNUVpGuRs4Yb-JU08jdJiyy9OxQYc',
    appId: '1:962831719512:ios:20fb275d0034aa6e4dbe2d',
    messagingSenderId: '962831719512',
    projectId: 'hrverse-a8dc5',
    storageBucket: 'hrverse-a8dc5.firebasestorage.app',
    iosBundleId: 'com.example.hrverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwkePe2VYZuJkzWtYNx9p9JfGO7AQvHC8',
    appId: '1:962831719512:web:6b1630f06073fed04dbe2d',
    messagingSenderId: '962831719512',
    projectId: 'hrverse-a8dc5',
    authDomain: 'hrverse-a8dc5.firebaseapp.com',
    storageBucket: 'hrverse-a8dc5.firebasestorage.app',
    measurementId: 'G-3BXNSCSVKK',
  );
}
